### ISSUE TITLE
Update CMake

### ISSUE THREAD

**Issue by Jovan-ux** [endurodave/SimpleSocketProtocol#1]
HI Dave, 
First of all, thank you for the great work you have done here. This is a great project and I would also like to use it. I will adapt this project for myself on CMAKE and accordingly I wanted to offer you my results. What do you think about it?

KR Joe

**Comment by Jovan-ux** [comment]
As i've just started, i think i could provide a unix hal&osal as well with a demo by using mqueues or something for IPC.

**Comment by endurodave** [comment]
Sure, I'll take a look if you have new HAL/OSAL and CMake. Thanks. Dave

**Comment by Jovan-ux** [comment]
I use the stack together with SLIP(e.g. this [one](https://github.com/marcinbor85/slip/tree/master)) This makes it easy to overcome the restriction on user data and send any amount of data. Thanks to the clever approach (everyone uses sockets!) it runs really smoothly. It's really great. Thanks Dave for the great work!
